In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
##+ - * /
import random
A=np.arange(6).reshape(3,2)
print('A = ');print(A,'\n')
B=np.arange(6,12).reshape(3,2)
print('B = ');print(B,'\n')
C=A+B
print('A + B = ');print(C,'\n')
D=B-A
print('A - B = ');print(D,'\n')
E=3*A
print('3 * A = ');print(E,'\n')
F=A/2
print('A / 2 = ');print(F,'\n')

A = 
[[0 1]
 [2 3]
 [4 5]] 

B = 
[[ 6  7]
 [ 8  9]
 [10 11]] 

A + B = 
[[ 6  8]
 [10 12]
 [14 16]] 

A - B = 
[[6 6]
 [6 6]
 [6 6]] 

3 * A = 
[[ 0  3]
 [ 6  9]
 [12 15]] 

A / 2 = 
[[0.  0.5]
 [1.  1.5]
 [2.  2.5]] 



In [3]:
##dot & cross
A=np.arange(4).reshape(2,2)
B=np.arange(4,8).reshape(2,2)
print('A =');print(A,'\n')
print('B =');print(B,'\n')
C1=np.dot(A,B)
C2=np.dot(B,A)
D1=np.cross(A,B)
D2=np.cross(B,A)
print('C1 =');print(C1,'\n')
print('C2 =');print(C2,'\n')
print('D1 =');print(D1,'\n')
print('D2 =');print(D2,'\n')

A =
[[0 1]
 [2 3]] 

B =
[[4 5]
 [6 7]] 

C1 =
[[ 6  7]
 [26 31]] 

C2 =
[[10 19]
 [14 27]] 

D1 =
[-4 -4] 

D2 =
[4 4] 



In [4]:
t1=np.array([-2,-2,1]).reshape(1,3);t2=np.array([1,-4,3])
print(np.cross(t1,t2))

[[-2  7 10]]


In [5]:
## Solution
A=np.array([[3,2,1],
            [1,2,3],
            [4,5,7]])
y=np.array([[5],[8],[7]])
print('Matrix A :');print(A,'\n')
print('Matrix y :');print(y,'\n')
inv_A=np.linalg.inv(A)
print('Inverse A :');print(inv_A,'\n')

I=np.dot(A,inv_A)
print('Matrix I :');print(I,'\n')

x=np.dot(inv_A,y)
print('Matrix x :');print(x,'\n')

Matrix A :
[[3 2 1]
 [1 2 3]
 [4 5 7]] 

Matrix y :
[[5]
 [8]
 [7]] 

Inverse A :
[[-0.25 -2.25  1.  ]
 [ 1.25  4.25 -2.  ]
 [-0.75 -1.75  1.  ]] 

Matrix I :
[[ 1.00000000e+00  1.33226763e-15 -6.66133815e-16]
 [ 1.11022302e-16  1.00000000e+00 -2.22044605e-16]
 [ 1.11022302e-16  4.44089210e-16  1.00000000e+00]] 

Matrix x :
[[-12.25]
 [ 26.25]
 [-10.75]] 

